SELECT *, 
CASE 
WHEN DATA_DE_NASCIMENTO < '1990-01-01' THEN 'Velhos'
WHEN DATA_DE_NASCIMENTO <= '1995-01-01' AND DATA_DE_NASCIMENTO > '1990-01-01' THEN 'Jovens'
WHEN DATA_DE_NASCIMENTO > '1995-01-01' THEN 'Crianças'
ELSE '-'
END AS CLASSIFICAÇÃO_IDADE

FROM tabela_de_clientes
	

SELECT *, 
CASE WHEN IDADE > 18 THEN 'S'
ELSE 'N'
END AS ADULTO,
CASE WHEN VOLUME_DE_COMPRA < LIMITE_DE_CREDITO THEN 'BOA'
ELSE 'RUIM'
END AS SITUAÇÃO_CLIENTE

FROM tabela_de_clientes
	


SELECT *, 
CASE WHEN IDADE > 18 THEN 'S'
ELSE 'N'
END AS ADULTO,

CASE WHEN SEXO = 'M' THEN 'Masculino'
WHEN SEXO = 'F' THEN 'Feminino'
ELSE '-'
END AS SEXO
  FROM sucos_vendas.tabela_de_clientes
